from google.genai import types

BUSINESS_TOOLS = [
    types.FunctionDeclaration(
        name="get_revenue",
        description="""Get revenue statistics including total revenue,
monthly revenue, daily revenue, completed orders,
sales performance, revenue trends and revenue analysis."""
    ),
    types.FunctionDeclaration(
        name="get_profit",
        description="""
Get revenue statistics including total revenue,
monthly revenue, daily revenue, completed orders,
sales performance, revenue trends and revenue analysis.
"""
    ),
    types.FunctionDeclaration(
        name="get_orders",
        description="""Get order statistics including total orders,
completed orders, delivered orders, pending orders,
rejected orders, total trays sold, order performance
and operational analysis."""
    ),
    types.FunctionDeclaration(
        name="get_expenses",
        description="""
Get overall expense statistics including
total expenses,
expense record count,
total business spending,
and expense summaries.
"""
    ),
    types.FunctionDeclaration(
        name="get_expense_categories",
        description="""
    Get expense category breakdown,
    largest expense category,
    category spending totals,
    expense analysis and spending patterns.
    """
    ),
    types.FunctionDeclaration(
        name="get_customers",
        description="""
Get customer statistics including top customers,
highest revenue customer, customer rankings,
customer performance, customer purchase history,
customer contribution and customer analysis.
"""
    ),
    types.FunctionDeclaration(
        name="get_customer_details",
        description="""
    Get detailed information about a specific customer,
    customer history,
    customer revenue,
    last order date,
    last delivery date,
    customer orders,
    customer purchases,
    and customer performance.
    """,
        parameters=types.Schema(
            type=types.Type.OBJECT,
            properties={
                "customer_name": types.Schema(
                    type=types.Type.STRING,
                    description="Business name of the customer"
                )
            },
            required=["customer_name"]
        )
    ),
    types.FunctionDeclaration(
        name="get_overview",
        description="""
Get complete business overview and business analysis
covering revenue, profit, expenses, customers,
orders, business performance, key insights,
recommendations and areas needing attention.
"""
    ),
    types.FunctionDeclaration(
            name="get_orders_between_dates",
            description="""
        Get orders, revenue and trays sold
        between two dates.
        Use for date range analysis,
        weekly reports,
        monthly reports,
        and custom date reports.
        """,
            parameters=types.Schema(
                type=types.Type.OBJECT,
                properties={
                    "start_date": types.Schema(
                        type=types.Type.STRING,
                        description="Start date YYYY-MM-DD"
                    ),
                    "end_date": types.Schema(
                        type=types.Type.STRING,
                        description="End date YYYY-MM-DD"
                    )
                },
                required=[
                    "start_date",
                    "end_date"
                ]
            )
        ),

        types.FunctionDeclaration(
            name="get_revenue_trends",
            description="""
            Analyze revenue growth trends.

            Returns:
            - current month revenue
            - previous month revenue
            - growth percentage
            - revenue trend
            - best performing month
            - highest revenue month

            Use when the user asks:

            - Is revenue growing?
            - Compare this month vs last month
            - Show revenue trend
            - Which month performed best?
            - Is business improving?
            - Revenue growth analysis
            """
        ),

        types.FunctionDeclaration(
            name="get_customer_rankings",
            description="""
            Customer Intelligence and Customer Ranking Analytics.

    Returns detailed customer rankings based on completed business orders.

    Provides:

    - VIP customer identification
    - Highest revenue generating customers
    - Highest tray purchasing customers
    - Customer leaderboard
    - Revenue contribution analysis
    - Order volume comparison
    - Customer performance comparison

    The function returns:

    - VIP customer
    - Top customers ranked by revenue
    - Top customers ranked by trays purchased
    - Total orders for each customer
    - Revenue generated by each customer
    - Tray quantities purchased by each customer

    Use this function whenever the user asks:

    CUSTOMER RANKING QUESTIONS

    - Who are my VIP customers?
    - Who is my best customer?
    - Who is my top customer?
    - Who is my most valuable customer?
    - Which customer contributes the most revenue?
    - Which customer generates the highest sales?
    - Which customer buys the most trays?
    - Who purchased the most trays?
    - Who placed the most orders?

    CUSTOMER LEADERBOARD QUESTIONS

    - Show customer rankings
    - Rank customers
    - Customer leaderboard
    - Top customers
    - Best customers
    - Customer performance ranking
    - Show customer intelligence
    - Customer analysis

    CUSTOMER COMPARISON QUESTIONS

    - Compare customers
    - Compare top customers
    - Which customer performs better?
    - Who should I focus on?
    - Which customers are most important?

    BUSINESS INSIGHT QUESTIONS

    - Which customers drive my business?
    - Which customers contribute most revenue?
    - Where should I focus customer growth?
    - Who are my key customers?
    - Which customers are worth retaining?

    Always prefer this function for customer ranking,
    customer leaderboard, customer value analysis,
    VIP customer identification, and customer intelligence questions.
            """
        ),




        types.FunctionDeclaration(
            name="get_business_health",
            description="""
            Perform complete business health analysis.

            Returns:
            - overall health score
            - business status
            - profitability analysis
            - strengths
            - weaknesses
            - operational issues
            - customer concentration risks
            - expense analysis
            - recommendations for improving profit and business performance

            Use when the user asks:
            - How healthy is my business?
            - What needs attention?
            - What is hurting profitability?
            - What should I focus on?
            - How can I improve?
            - Give recommendations
            - Strengths and weaknesses
            - Business analysis
            """
        ),

        types.FunctionDeclaration(
            name="get_order_records",
            description="""
        Get actual order records.

        Use when the user asks:
        - show orders
        - order history
        - recent orders
        - customer orders
        - completed orders
        - pending orders
        - orders between dates

        Returns detailed order records instead of summaries.
        """,
            parameters=types.Schema(
                type=types.Type.OBJECT,
                properties={
                    "customer_name": types.Schema(
                        type=types.Type.STRING
                    ),
                    "status": types.Schema(
                        type=types.Type.STRING
                    ),
                    "start_date": types.Schema(
                        type=types.Type.STRING
                    ),
                    "end_date": types.Schema(
                        type=types.Type.STRING
                    ),
                },
            ),
        ),
]